# Generated by Django 5.1 on 2024-09-24 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0008_delete_user_registration_prdt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=60)),
                ('status', models.BooleanField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='productsCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_quantity', models.IntegerField()),
                ('Approval_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approval_user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
