# Generated by Django 5.1 on 2024-09-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_register_email_alter_register_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_prdt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('password', models.CharField(max_length=20)),
                ('panel', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=20)),
            ],
        ),
    ]
