# Generated by Django 5.1 on 2024-09-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_registration_prdt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration_prdt',
            new_name='User_Registration_prdt',
        ),
    ]
