# Generated by Django 5.1 on 2024-09-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_registration_prdt_user_registration_prdt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration_prdt',
            name='panel',
        ),
    ]
