# Generated by Django 5.1 on 2024-09-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_productuser_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Registration_prdt',
        ),
    ]
